services:
  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: mqtt-mosquitto
    ports:
      - "1883:1883"
      - "8883:8883"
      - "9001:9001"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ./mosquitto.passwd:/mosquitto/config/mosquitto.passwd:ro
      - ./certs:/mosquitto/certs:ro
